name: commercepal
description: An ecommerce site

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.3+15

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  bloc_test: ^9.1.0
  cupertino_icons: ^1.0.2

  # di
  injectable: ^2.1.0
  get_it: ^7.2.0

  bloc: ^8.1.0
  flutter_bloc: ^8.1.1
  freezed_annotation: ^2.2.0

  # ui
  flutter_screenutil: ^5.8.1
  animated_text_kit: ^4.2.2
  flutter_svg: ^1.1.6
  carousel_slider: ^4.2.1
  flutter_rating_bar: ^4.0.1
  cached_network_image: ^3.2.3
  intl: ^0.17.0
  image_picker: ^0.8.7

  # network
  dio: ^4.0.6

  # databases
  floor: ^1.4.1
  sqflite: ^2.2.4+1
  flutter_secure_storage: ^7.0.1

  path_provider:
  fimber: ^0.6.6
  device_info_plus: ^8.1.0
  android_id: ^0.1.3+1
  phone_number: ^1.0.0
  email_validator: ^2.1.17
  url_launcher: ^6.1.9
  store_redirect: ^2.0.1
  sms_autofill: ^2.3.0
  build_runner: ^2.4.7
  build: ^2.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  injectable_generator:
  floor_generator:
  freezed:
  test:

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/icons/
    - assets/svgs/
    - assets/images/

  fonts:
    - family: Sora
      fonts:
        - asset: assets/fonts/Sora-Bold.ttf
          weight: 700
        - asset: assets/fonts/Sora-Light.ttf
          weight: 300
        - asset: assets/fonts/Sora-Medium.ttf
          weight: 500
        - asset: assets/fonts/Sora-Regular.ttf
          weight: 400
